{% set name = "nds2-client-swig" %}
{% set version = "0.16.1" %}
{% set sha256 = "abcd4b85cf033c685a82a36d0d4ca4e43e0f0bb7a763ff18a6bd32e3402ec292" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - make
    - cmake >=3.6
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - nds2-client >=0.15.3
    - swig >=3.0.7

outputs:
  - name: nds2-client-swig
    script: install-interface.sh
    requirements:
      build:
        - cmake
        - make
  - name: python-nds2-client
    script: install-python.sh
    requirements:
      build:
        - cmake >=3.6
        - make
      host:
        - swig >=3.0.7
        - {{ pin_subpackage('nds2-client-swig', exact=True) }}
        - nds2-client >=0.15.3
        - python
        - numpy
      run:
        - nds2-client >=0.15.3
        - python
        - {{ pin_compatible('numpy') }}
    test:
      imports:
        - nds2
    about:
      home: https://wiki.ligo.org/DASWG/NDSClient
      license: GPLv3
      license_family: GPL
      license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
      summary: Python extensions for NDS2
      description: |
        This provides python wrappers for the nds2 client.

about:
  home: https://wiki.ligo.org/DASWG/NDSClient
  license: GPLv3
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  summary: NDS2 Client interface SWIG wrappings

extra:
  recipe-maintainers:
    - duncanmmacleod
