travis:
  secure:
    BINSTAR_TOKEN: vM11hcpKAtijIMTS+ThQNx2P9BWaN5QZErM5cvGLclH26JQXlFsB6sDQQn6r6CPRDMb0Atvm263tyIFTaaWIsrCGkOFgH5lpBOdf79ZYX9v+tJosOJ6uhxdCvpKX+HWiqsyym4qTHB5CO8PSpWO/mSjHfbDoB3ATZp6fE0SzUrJvCwQAbbO0/mUkcYzoHuwRnH1E0VYoMzEVgSzHtZJfmS58EdtLaW7+NnHByMvjAG4Js4CeyjzP3XdnPRYxOcK6aWws0XzF3uY9lVh2/nIEzZvgJSXVnxNs9aMe1LE7CTA3bS7agccmCIq4m9ZNdvRKkR0TTTcx+gYqD92INerdJT1YWFV+v2JAJHHLzrbHRbcIP2FOQrCZ8V/tqupoZ08jtfMVpZWZReFp7ryS6nrt3sLpGehvpp4HgWfKUpmxfWHo+cWDOT5fZsfzWwW63tl327zWI/FjWLcYNAVOCB6HFiCMMTUs8AQQJx1uN6QnTxkRk7CvdTU2PwVPnF9MUfrK1VdMV1/s1et95j2hXXU/JITHv8xmUO3dYuipXBKwPW+dprs8TRTuGC4qQDUuCdWYfXSwJV/YQH0F4rYTl3CJN7VXcxk8AbFDwhIzJzN7W8CX/31FhRXIiLGOvTdvLzYtURkT1xa7RqXlfzJso+xaPBh1b4n1vpGflsmYoVd4j7Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
